### ISSUE TITLE
Build fail Qt5 Linux

### ISSUE THREAD

**Issue by billotronic** [yegord/snowman#100]
http://dpaste.com/37SSS2M fails

http://dpaste.com/3SNBVWH 

This box has built against Qt5 so I'm not sure what the issue is. Worked fine under Qt4.

**Comment by techbliss** [comment]
is the file libGL.so in your folder /usr/lib/x86_64-linux-gnu/
Says it cannot find that file.

**Comment by billotronic** [comment]
Yes, the second paste lists it and I also laid eye balls on the file within the folder. That is what struck me as strange.

**Comment by yegord** [comment]
CMake printed you a stack trace showing where exactly the Qt5 CMake script
has failed. You can read the script, and it might give you some ideas.

If the script looks legit, but does not work as expected, run cmake under
strace, and see what the former is actually doing and why it fails.

-- 
Yegor Derevenets

**Comment by techbliss** [comment]
maybe this
[qt can't find GL/gl.h but libGL.so exists ](http://askubuntu.com/questions/574217/qt-cant-find-gl-gl-h-but-libgl-so-exists)

**Comment by billotronic** [comment]
@techbliss ooo good thought, but no dice, already have the -dev's.

@yegord as soon as I can get some time I will investigate further and report back.
