### ISSUE TITLE
HOW THE HECK DO I GET CODE?

### ISSUE THREAD

**Issue by Brian151** [yegord/snowman#101]
My friend tried using this for me (my computer simply can't handle it), he can't get the code

Can only save the dot file, and the code window absolutely WON'T copy its text to anything

Also, should definitely have better usage documentation in general

**Comment by yegord** [comment]
On Nov 18, 2016 9:23 AM, "Brian" <notifications@github.com> wrote:
> Can only save the dot file, and the code window absolutely WON'T copy its
text to anything
Copy to clipboard should just work. If it does not, please provide the
versions of your OS, Qt, IDA (if you are talking about the plugin) and the
exact steps to reproduce the problem. Also, you could try 'Save As...' from
the text widget's context menu.

> Also, should definitely have better usage documentation in general
You are welcome to write one and submit a patch.

-- 
Yegor Derevenets
