### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by TheClockworker** [yegord/snowman#107]
![snowman decompiler error](https://cloud.githubusercontent.com/assets/25556949/22637626/ec246608-ec10-11e6-892f-498954e8e87e.png)

**Comment by Deathsbreed** [comment]
You may want to specify how the error occurred, did it happen at startup? Do you have any configurations (if so please give a pastebin of them)?

**Comment by TheClockworker** [comment]
I'm sorry for the lack of detail in my error report. Hopefully, I can clear up the issue with this post. I was attempting to decompile a batch of code from a program containing genetic algorithms and neural networks. I had no special configurations set up. I was using the release version of the Snowman decompiler extracted from the .Zip file on the main website.

**Comment by yegord** [comment]
Could you provide the input file and the exact steps to reproduce the problem?
The input file you can send by e-mail to snowman@derevenets.com, for example.

**Comment by TheClockworker** [comment]
I have sent snowman@derevenets.com an email with a link to the original input file and description of what lead to the error.

**Comment by yegord** [comment]
Did you decompile the whole .text section? If yes, you might have gone out of memory, and that was the reason of the assertion failing. You can consider decompiling individual functions (IDA plugin makes it easy) or smaller chunks of code.

**Comment by TheClockworker** [comment]
Hmm, I'm still encountering the error even though I broke up the code into eighths. The term != nullptr error just occurs quicker each time I break the code block smaller. I will continue to try to break the code into smaller blocks to find where the error is exactly. Try reproducing my error by attempting to decompile between address 401000 - 471025 of the .txt part of the exe.

**Comment by TheClockworker** [comment]
Update: I was analyzing the error and further discovered that Snowman.exe continues to persist in my memory after it crashes. I have to terminate it's process tree in Task Manager to free up the gigabyte of RAM it takes up. I have a theory, it may sound far fetched, but I think that the genetic algorithms are being activated in memory as they are being analyzed and decompiled. A genetic algorithm reproduces itself in memory like a virus if left unchecked. That may explain why Snowman.exe is running out of memory so quickly even though I'm giving it manageable chunks of code.

**Comment by TheClockworker** [comment]
Update 2: I received a unknown error and crash type when decompiling between address 681100-751125 of the .txt part of the exe.

**Comment by yegord** [comment]
> Update 2: I received a unknown error and crash type when decompiling between address 681100-751125 of the .txt part of the exe

Works fine on 64-bit Linux build. Probably, does not work on Windows due to the smaller default stack size (1MB on Windows vs 8MB on Linux). Although it works fine, it produces 13 megabytes of text. It is unclear why one would want to get so much decompiled code and what one would want to do with it...

> I recommend you try reproducing my error by attempting to decompile between address 401000 - 471025 of the .txt part of the exe.
Yep, this reproduces the problem. Thanks.
