### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by Deathsbreed** [yegord/snowman#112]
I've been looking through snowman to look into packaging it, however there is a major problem... which is that I cannot see any license files. Could you please add a license file to the project?

Thank you.

**Comment by jrmuizel** [comment]
https://github.com/yegord/snowman/blob/master/doc/licenses.asciidoc

**Comment by Deathsbreed** [comment]
I'm a little confused as to why it's in `doc/`, but I will see myself out... * walks out in shame *
