### ISSUE TITLE
Add support for 'thiscall' calling convention

### ISSUE THREAD

**Issue by jrmuizel** [yegord/snowman#12]
This can presumably be detected by looking for reads from 'ecx' without initializing it to anything and 'ret n' at the end.

**Comment by yegord** [comment]
There is a chicken and egg problem: to detect a calling convention like you propose, you need dataflow information, to get the dataflow information, you need calling conventions known. Maybe the following solution will work satisfactory: https://github.com/yegord/snowman/commit/50bffeb6aad30ab55d9322fba0fc19a87f41e2be

It would be great if you could contribute a test (I do not have MSVC nearby).

**Comment by jrmuizel** [comment]
Are we using the presence of 'ret n' instructions to detect stdcall? It didn't look like we were.

**Comment by mrexodia** [comment]
@jrmuizel I don't believe you can detect `stdcall` in a definitive way using that method. But it might be possible to do with some heuristics like you propose.

**Comment by jrmuizel** [comment]
@mrexodia What are the circumstances that you are thinking of where you have stdcall but no 'ret n' or vice versa?

**Comment by yegord** [comment]
Added recognition of 'ret n': https://github.com/yegord/snowman/commit/915b6f82e2244d2d3a22e6852d97f0e465a3de72.

**Comment by mrexodia** [comment]
@jrmuizel There is for example no way to determine the calling convention of a function without arguments :smiley:

**Comment by jrmuizel** [comment]
I did some basic testing of this and it seemed to work ok. I'll try to put together some test cases next week.

**Comment by yegord** [comment]
I have pushed my changes to master: 6cd57531239684438182311232b62279283e20d4, 8dcd9e24c2972b5c712f1aebbd965edf6ddbc1d6, 4c77102a1e9a1b6e8f57f4b75af8b9f305f6c5a5.

Ideally, we should have some information about the compiler or C++ ABI used, and not consider passing `this` through ecx for non-thiscall-capable compilers. Maybe in future...
