### ISSUE TITLE
command line usage ?

### ISSUE THREAD

**Issue by rofl0r** [yegord/snowman#124]
the README mentions that snowman can be used on the command line, so i built it on a dedicated server (since QT5 is too big to be installed locally).
the server doesn't have an X server, and when i try to run it, i get:
```
./snowman/snowman --help
QXcbConnection: Could not connect to display
Aborted
```
so how can i run the command line mode ? i.e. pass filename of executable, get decompiled code on stdout or into a file ?

**Comment by rofl0r** [comment]
my plan was actually to setup some kind of mini-webservice on that machine, so i can use it from a webinterface whenever i need it.

**Comment by yegord** [comment]
`nocode` is the command line tool that you want.

**Comment by rofl0r** [comment]
thanks, that worked. maybe it would make sense to mention that somewhere ? maybe in the README ?

**Comment by yegord** [comment]
Yep. Added a mentioning on the website. Have a nice holiday.

**Comment by rofl0r** [comment]
thanks for the mentioning. though i didn't even know that website exists, googling for snowman landed me straight here in the repo...
