### ISSUE TITLE
Stdcall32CallingConvention possible bug

### ISSUE THREAD

**Issue by 8BitPimp** [yegord/snowman#133]
The Stdcall32CallingConvention has its return value specified as a 16 bit register AX instead of the 32bit EAX.  is this correct behavior?

See:
arch\x86\CallingConvensions.cpp:155

```c
addReturnValueLocation(X86Registers::ax()->memoryLocation());
```
Should this rather be:
```c
addReturnValueLocation(X86Registers::eax()->memoryLocation());
```

**Comment by yegord** [comment]
Exactly! Thanks, fixed.
