### ISSUE TITLE
Cannot build snowman using Qt 4.8 and MinGW-W64-builds-4.2.0

### ISSUE THREAD

**Issue by bugadani** [yegord/snowman#138]
I've spend two days trying to build snowman and the farthest I got using the above qt-mingw combo is a ton of linking errors like this (Example is the QString destructor):

`C:/Qt/4.8.7/src/corelib/tools/qstring.h:880: undefined reference to `_imp___ZN7QString4freeEPNS_4DataE'`

I've followed the installation doc by the letter on a Windows 10 machine and just couldn't get it to work. If this is caused by me somehow, I would like to ask for some help figuring it out, otherwise please make a note in the docs. Thanks.

**Comment by yegord** [comment]
Did you build Qt in `QT` namespace?
If yes, did you pass `-D QT_NAMESPACE=QT` to cmake at the configuration step?

**Comment by bugadani** [comment]
Yes I did both, I double checked, however I could only have passed it as -DQT_NAMESPACE in command line or else I had an error. Maybe I passed it incorrectly? I can see that the namespace is not present in my error message.

**Comment by yegord** [comment]
Both work for me. Although, it is strange that the one with the space did not.

Yep, if Qt is built in a namespace, then it completely makes sense that a Qt symbol outside of the namespace is not found.

Could you provide the compilation command that fails?
The exact command (with all arguments), plus its output.

**Comment by yegord** [comment]
Actually, a complete build log, including configuration command would be even better.

**Comment by bugadani** [comment]
My experiment-build that assumes qt was built without a namespace just finished successfully. Apparentally, my QT was (in all my trials) somehow built without a namespace. In this case, the error message sounds backwards (undefined reference to a symbol outside the namespace, when the one in the namespace is missing? do I read that tangled name wrong?) but a) I haven't given it much thought and b) not your doing. So thanks for your insight and I should meditate on how Qt got compiled incorrectly. Maybe it didn't compile at all and I got the default libs that were installed?

Doesn't matter, the point is, it was user error :( Thank you for your time and insight.

**Comment by yegord** [comment]
Well, if you did not built it in a namespace, then just do not pass -D QT_NAMESPACE=QT to CMake, and Snowman should build fine.

**Comment by bugadani** [comment]
I did pass QT_NAMESPACE=<empty> and it built fine, installed fine but now it doesn't start with "The procedure entry point _Z18q...... could not be located in the dynamic link library" I will fiddle around with it and if I finally get it working, I'll write back with my results and maybe write a patch that clears up my confusions in the install docs. In the mean time, could you please push a prebuilt version for idiots like me?

**Comment by yegord** [comment]
There are some not too fresh binaries at derevenets.com
Do you want fresh builds of the master?
I could make a release, but it will take several hours to build and upload.

**Comment by bugadani** [comment]
Thanks, I managed to solve my issue by manually copying the appropriate qt dlls and my snowman build now starts. But I think a fresh set of binaries could be helpful to some.
