### ISSUE TITLE
IDA v7 support

### ISSUE THREAD

**Issue by xorstream** [yegord/snowman#141]
The IDA SDK API has changed in IDA v7.
Also IDA has moved to 64bit, so all plugins also need to be built as 64bit.

Any chance of premade binaries with support for IDA v7?

**Comment by yegord** [comment]
Did you look into what has been changed?
If all what is needed is to rebuild the plugin for x86-64 and link against a new library, there there is definitely a chance.

**Comment by xorstream** [comment]
I've done a pr #142 with the API changes for IDA v7.
I lack the correct dev environment to build and test them though.

**Comment by xorstream** [comment]
Looking forward to prebuilt binaries for IDA v7 support soon ;)

**Comment by yegord** [comment]
Done.

**Comment by xorstream** [comment]
thanking you ;)
