### ISSUE TITLE
Cannot change colors

### ISSUE THREAD

**Issue by blue-devil** [yegord/snowman#146]
Hello i am using IDA Pro with dark color scheme. Unfortunately colors of Snowman are static and i cannot change. I am not sure if i couldnt manage to do it or is it impossible already?
Thanks for everything.

**Comment by yegord** [comment]
Snowman windows should inherit the style sheets of the parent Qt widgets belonging to IDA.
So, by changing the IDA's style sheet you should be able to change the appearance of Snowman as well.
Most likely, you can tell IDA which style sheet to use by providing a qss file as `-stylesheet` command line argument.

Alternatively, you can always apply a custom style sheet directly to Snowman windows by loading it via the **File/Load Style Sheet** menu item.
The loaded style sheet will be remembered, once you close the Snowman window.
It will be loaded next time you open new windows.

You can use https://github.com/yegord/snowman/blob/master/dark.qss as a starting point for your dark style sheet.

**Comment by blue-devil** [comment]
This is awesome! Thanks for your reply. I am going to edit style sheet and share with you.
Closing Topic :)
