### ISSUE TITLE
Deliver snowman with Docker

### ISSUE THREAD

**Issue by guyou** [yegord/snowman#147]
I've just tried to build snowman from a Debian testing and it does not works because of the version of CMake (currently 3.7 while snowman requires 3.9).

Delivering such software for Linux can be a headache due to variety.

Is it possible to create a Docker container to run the cli interface?

**Comment by yegord** [comment]
CMake 3.9 is available in Debian Testing.
```
[yegor@yegor ~]$ apt-cache policy cmake
cmake:
  Installed: 3.9.5-1
  Candidate: 3.9.5-1
  Version table:
 *** 3.9.5-1 990
        990 http://httpredir.debian.org/debian testing/main amd64 Packages
        500 http://httpredir.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     3.7.2-1 500
        500 http://httpredir.debian.org/debian stable/main amd64 Packages
```

**Comment by guyou** [comment]
Oops... effectivelly: there was an issue in my APT settings. Sorry!

**Comment by yegord** [comment]
Coming back to the original question, I think, Snowman is pretty easy to build on any Linux distribution, so, I doubt I am willing to spend time on providing docker images with it.

Also, CMake 3.7 should be enough for a successful build (I wanted to use GREATER_EQUAL operator, this is why I bumped the required version, not too accurately, apparently). I have updated the requirements.
