### ISSUE TITLE
ambiguous declarations

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#15]
gcc 4.6.4 yells on this:
[ 25%] Building CXX object nc/core/CMakeFiles/nc-core.dir/ir/cgen/CodeGenerator.cpp.o
In file included from /home/markus/Downloads/snowman/src/nc/core/likec/FunctionDeclaration.h:31:0,
                 from /home/markus/Downloads/snowman/src/nc/core/likec/FunctionDefinition.h:32,
                 from /home/markus/Downloads/snowman/src/nc/core/ir/cgen/CodeGenerator.cpp:42:
/home/markus/Downloads/snowman/src/nc/core/likec/ArgumentDeclaration.h: In constructor ‘nc::core::likec::ArgumentDeclaration::ArgumentDeclaration(nc::core::likec::Tree&, const QString&, const nc::core::likec::Type*)’:
/home/markus/Downloads/snowman/src/nc/core/likec/ArgumentDeclaration.h:47:48: error: conversion from ‘int’ to ‘std::unique_ptr<nc::core::likec::Expression>’ is ambiguous
/home/markus/Downloads/snowman/src/nc/core/likec/ArgumentDeclaration.h:47:48: note: candidates are:
/usr/include/c++/4.6/bits/unique_ptr.h:136:17: note: constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Tp = nc::core::likec::Expression, _Dp = std::default_delete<nc::core::likec::Expression>, std::nullptr_t = std::nullptr_t]
/usr/include/c++/4.6/bits/unique_ptr.h:120:7: note: std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>::pointer) [with _Tp = nc::core::likec::Expression, _Dp = std::default_delete<nc::core::likec::Expression>, std::unique_ptr<_Tp, _Dp>::pointer = nc::core::likec::Expression*]
make[2]: *** [nc/core/CMakeFiles/nc-core.dir/ir/cgen/CodeGenerator.cpp.o] Error 1
make[1]: *** [nc/core/CMakeFiles/nc-core.dir/all] Error 2

**Comment by nihilus** [comment]
Verified as fixed: thx.

**Comment by yegord** [comment]
Just curious, why do you still use 4.6? :-)

**Comment by nihilus** [comment]
We have a streamlined Linux setup at my day work based on Ubuntu Precise LTS... When I started with embedded systems people used Debian Stable. Vendors still ship GCC 3.4-based toolchains.

I used to fix lots of bugs in GNU Gnash by compiling it on my SGI Octane2 with MIPSPro C/C++ ;-)
