### ISSUE TITLE
MSVC5 - Strings Not Expanded / Shown

### ISSUE THREAD

**Issue by steve-gray** [yegord/snowman#151]
When decompiling an old game (Total Annihilation), I'm noticing that unlike IDA - when the code is produced, none of the strings are resolved in the arguments of functions - making code very hard to read/work with. They persistently appear as 0x100abcdef references to the offset in the data segments for the file.

The program is a MSVC5 compiled (debug, but without pdb present) executable.

I'm wondering, am I missing a trick here / not setting a required option somewhere?

(PS: Fantastic project, pretty impressive code output and speed)

**Comment by yegord** [comment]
All constants are generated by `DefinitionGenerator::makeConstant`, see https://github.com/yegord/snowman/blob/master/src/nc/core/ir/cgen/DefinitionGenerator.cpp#L1106. Unless you undefined NC_PREFER_CSTRINGS_TO_CONSTANTS in config.h and recompiled the plugin, the function will try to generate a C string if the constant looks like a pointer to an ASCII string. Apparently, the (pretty basic) heuristic is not working in your case. Can you think of a probable cause by looking at the code?

**Comment by steve-gray** [comment]
Could it be that the parameter is a pointer to a string?

__Raw__
```
push dword 0x10028474
```

__IDA Dissasembly__
```
push offset aConnect_to  ; "connect_to"
````

__Snowman Disassembly__
```
eax9 = fun_10005abc(ecx, a2, 0x110028474, edi5, ebx6, v7, v8)
````

(Where the 0x address is the zero terminated ASCII string "connect_to")
[Rover.dll.zip](https://github.com/yegord/snowman/files/1594077/Rover.dll.zip)

**Comment by yegord** [comment]
> Perhaps passing strings that way causes the pointee() checks to skip the creation of a string.

Unfortunately, the tree inspector does not show type information at the moment, so, you cannot look it up in the GUI. Perhaps, I should fix that...

What is the address of the call?

**Comment by steve-gray** [comment]
@yegord, sorry for the delay. An example function in the attached DLL is at 14118h, which handles the command generation for a directive 'create_room'. Example instructions with strings:

- 14159h - pushes an offset to a string labelled create_room
- 14171h - pushes an offset to a string labelled area_id

Any ideas?

**Comment by yegord** [comment]
```diff
diff --git a/src/nc/core/ir/cgen/DefinitionGenerator.cpp b/src/nc/core/ir/cgen/DefinitionGenerator.cpp
index e84f7bf..e80d71d 100644
--- a/src/nc/core/ir/cgen/DefinitionGenerator.cpp
+++ b/src/nc/core/ir/cgen/DefinitionGenerator.cpp
@@ -1117,7 +1117,7 @@ std::unique_ptr<likec::Expression> DefinitionGenerator::makeConstant(const Term
 #endif
 
 #ifdef NC_PREFER_CSTRINGS_TO_CONSTANTS
-    if (!type->pointee() || type->pointee()->size() <= 1) {
+    {
         auto isAscii = [](const QString &string) -> bool {
             foreach (QChar c, string) {
                 if (c >= 0x80 || (c < 0x20 && c != '\r' && c != '\n' && c != '\t')) {
```
seems to fix the problem. Do you need a build with the fix?

**Comment by steve-gray** [comment]
Yes please: Win x64 if possible!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steve-gray** [comment]
Scratch that @yegord: I've managed to build myself an OSX binary (brew install cmake, ninja, cartr/qt@4, then run make 2-3 times).  Can confirm it's decompiling beautifully, strings and all! 

Thanks for turning around the fix.

**Comment by yegord** [comment]
Made a release anyway. Enjoy!
