### ISSUE TITLE
does snowman handle "stack base pointer refrence"  to "local variable" ?

### ISSUE THREAD

**Issue by anywhereyang** [yegord/snowman#167]
the  asm  :
10001118:	lea eax, [ebp+0xfffffde8]
1000111e:	push eax
1000111f:	push 0x0
10001121:	call dword [0x1000d038]

decomplie to the like c code : 
v13 = reinterpret_cast<struct s0*>(reinterpret_cast<uint32_t>(ebp1) + 0xfffffde8);
    GetModuleFileNameW();

the ideal code is:
char v8[];
GetModuleFileNameW( 0, v8 );  //  just guess

**Comment by yegord** [comment]
Yes, ideally, one should build a map of the function's stack frame and translate pointers to the stack into addrofs of local variables (e.g., arrays as in your example).
If you know which variable is where on the stack (and Snowman actually knows this), you can even estimate the sizes of the arrays on the stack.
All this is known to work but not implemented yet.

**Comment by anywhereyang** [comment]
is any update for this?

**Comment by yegord** [comment]
Well, I do not have plans to implement the stack map myself.
