### ISSUE TITLE
why not handle case Statement::HALT:  in DefinitionGenerator::doMakeStatement  ?

### ISSUE THREAD

**Issue by anywhereyang** [yegord/snowman#168]
mov al,0
retn 

it will recognize no return  while  fucntion no refrence ,

**Comment by yegord** [comment]
I have not understood how the name of the issue is related to the description of the issue.
The halt statement denotes that the execution of a program stops at this point, it does not denote a return from the function.
A return in C code is generated whenever the decompiler sees a jump and sees that this jump is to the return address.
You did not provide a minimal example, so I cannot say why the return is not generated in your case.

**Comment by anywhereyang** [comment]
there is some trouble to prevent visit github,so i send email to you!

there is a minimal example,

the ida opcode is :
.code:0002DAE1 48                             ARGS
.code:0002DAE2 04                             push_imm             4
.code:0002DAE3 24                             push_local_word            ;  push word [ebp+4];
.code:0002DAE4 00                             push_imm             0
.code:0002DAE5 24                             push_local_word            ;  push word [ebp+0];
.code:0002DAE6 08                             push_imm             8
.code:0002DAE7 25                             push_local_ref             ;  lea tmp, [ebp+8] ,push tmp
.code:0002DAE8 0C                             push_imm             0Ch
.code:0002DAE9 25                             push_local_ref             ;  lea tmp, [ebp+c] ,push tmp
.code:0002DAEA 49 00 00 36 4F                 CALL                sub_3113A
.code:0002DAEF 3A                             NOT                      
.code:0002DAF0 44 00 04                       JE                  loc_2DAF5
.code:0002DAF3 00                             push_imm             0     ;  push 0
.code:0002DAF4 4A                             RET                        ;  pop eax ;retn 
.code:0002DAF5                ; ---------------------------------------------------------------------------
.code:0002DAF5
.code:0002DAF5                loc_2DAF5:                              ; CODE XREF: MC_EDC17_RTIO_Start_PartReg+32j
.code:0002DAF5 01                             push_imm             1
.code:0002DAF6 4A                             RET
.code:0002DAF6                MC_EDC17_RTIO.Start_PartReg endp


the smartdec decomplied result is :
   eax9 = (int32_t)func_3113a(ebp1 + -12, ebp1 + -8, arg1, v8);
    if (!~eax9) {
        return 1;
    } else {
        return 0;
    }


the snowman deomplied result is :
*int16_t*(&v6) = v7;
    eax8 = fun_3113a(int32_t(__zero_stack_offset()) - int32_t("\\MAN cats II\\RUNTIME\\MonConfigFiles\\%d"), int32_t(__zero_stack_offset()) - int32_t("I"), a1, v6);
    if (!~eax8) {
    }

there is 2 problom of snowman:
\first :
   no generated return 1 and return 0, 
\second:
   no generated local variable refrence( liked c code : func_3113a( &v_0xC, &v_0x8, arg1, v8) ) 

the InstructionAnalyzer code of snowman (and smartdec liked this )  is :
            switch( instNum )
            {
             case push_imm:
                  if (instNum >= (int)mnemonics::PUSH_IMM_0 && instNum <= (int)mnemonics::PUSH_DD)
		{
			int tmp = instNum <= (int)mnemonics::PUSH_IMM_1F ? instNum : instr->operand(0)->asConstant()->value().value();
			syntaxTree.push(tmp);
		}
                  break;
            case RET:
            	if (syntaxTree.size())
		{
		          auto tmp = syntaxTree.top();  syntaxTree.pop();
			 _[ regizter(Pal2Registers::eax()) ^= constant(tmp, 32) ];
		}
		else
		{
		         _[ POPTo(regizter(Pal2Registers::eax())) 	];
		}
                  break;
           }
   

________________________________________
发件人: yegord [notifications@github.com]
发送时间: 2018年5月29日 21:18
收件人: yegord/snowman
抄送: anywhereyang; Author
主题: Re: [yegord/snowman] why not handle case Statement::HALT: in DefinitionGenerator::doMakeStatement ? (#168)

I have not understood how the name of the issue is related to the description of the issue.
The halt statement denotes that the execution of a program stops at this point, it does not denote a return from the function.
A return in C code is generated whenever the decompiler sees a jump and sees that this jump is to the return address.
You did not provide a minimal example, so I cannot say why the return is not generated in your case.

―

**Comment by yegord** [comment]
On Tue, May 29, 2018 at 06:10:17PM -0700, anywhereyang wrote:
> no generated return 1 and return 0, 

Well, AFAIU you have implemented a custom architecture. In the
description of RET semantics in InstructionAnalyzer code that you
provided I see no generation of a jump statement from which Snowman
could understand that there is a return. Let's add it and see what
happens.

> \second:
>    no generated local variable refrence( liked c code : func_3113a( &v_0xC, &v_0x8, arg1, v8) ) 

As I already replied, this is not implemented.

-- 
Yegor Derevenets

**Comment by anywhereyang** [comment]
am i need to add  jump to eip  statement liked x86architecture , or others?

**Comment by anywhereyang** [comment]
what is "AFAIU" ? a acronym ?

**Comment by Nable80** [comment]
> what is "AFAIU" ? a acronym ?

"As far as I understand". See also AFAIR ("...remember") and AFAIK ("... know").

**Comment by yegord** [comment]
> am i need to add jump to eip statement liked x86architecture , or others?

You need to jump to wherever address the RET jumps in your architecture.

For example, on x86 RET jumps to the address on the top of the stack:
```
_[jump(*regizter(sp))];
```
(In the actual code it is written as two statements involving the instruction pointer register only in order to handle the RETn case correctly.)

You will also need to tell the decompiler where the return address is going to reside according to the calling convention, similarly to how it is done for x86: https://github.com/yegord/snowman/blob/6b766ea54a60a524cca72e857d6a79589ce40553/src/nc/arch/x86/CallingConventions.cpp#L112

**Comment by anywhereyang** [comment]
i done what you say , but result not correct,
`
.code:0002DAEA 49 00 00 36 4F                 CALL                sub_3113A
.code:0002DAEF 3A                             NOT
.code:0002DAF0 44 00 04                       JE                  loc_2DAF5
.code:0002DAF3 00                             push_imm             0
.code:0002DAF4 4A                             RET

case mnemonics::RET:
				{
					_[ regizter(ip) ^= *regizter(bp) ];  
					if (syntaxTree.size())
					{
						auto tmp = syntaxTree.top();  syntaxTree.pop();
						_[ regizter(Pal2Registers::eax()) ^= constant(tmp, 32) ];
					}
					else
					{
						_[ POPTo(regizter(Pal2Registers::eax())) ];
					}
					_[jump(regizter(ip))];
				}
				break;

result below:
eax10 = fun_3113a(v8, v9, a1, v6);
    if (~eax10) {
        return "CAS_MIDI";    // it should be "return 1;"
    } else {
        return "ECAS_MIDI";  // it should be  "return 0;"
    }
`

**Comment by yegord** [comment]
Probably you have some ASCII data in your executable image at address 0.
Snowman optimistically assumes that you return a pointer to this data and substitutes the value of the pointer with the ASCII string at this pointer.
Do you really have a section at address 0 in your input executable?

**Comment by anywhereyang** [comment]
yes.there is a string at address 0.  

 there is no problem if the operand is a pointer ,but a constant should not to conversion ...

**Comment by yegord** [comment]
Unfortunately it is often the case that you do not know that something is a pointer, although it is and points to an ASCII string.

I guess, you can improve the heuristic to work better in your case: https://github.com/yegord/snowman/blob/master/src/nc/core/ir/cgen/DefinitionGenerator.cpp#L1119
