### ISSUE TITLE
some problem while write value to local variable

### ISSUE THREAD

**Issue by anywhereyang** [yegord/snowman#169]
```
.pcode:00003F1E                sub_3F1E()                              ; CODE XREF: sub_5B0F+29P
.pcode:00003F1E                                                        ; .pcode:00005BC9P
.pcode:00003F1E 4B 00 0E                       ALLOC    0Eh
.pcode:00003F21 00                             push_imm  0  ;push 0  ,, the value
.pcode:00003F22 0C                             push_imm  0Ch ;push C ,, the offset
.pcode:00003F23 6C                             SLBP            ; mov [ebp+c] , 0 ,, mov the value to the offset
.pcode:00003F24 48                             ARGS 

and i handle the instruction  with the code below:
case mnemonics::SLBP:
case mnemonics::SLWP:{
		assert(syntaxTree.size() >0 && "the syntaxTree must be not empty");
		auto bpOffset = fixOffset( argCount,allocSize,syntaxTree.top() ); syntaxTree.pop();
		if (syntaxTree.size()){
			//auto tmp = syntaxTree.top(); syntaxTree.pop();
			auto tmp = syntaxTree.top(); syntaxTree.pop();
			_[*(regizter(bp) + constant(bpOffset))  ^= constant(tmp)];   //
			}
			else
			{
				auto tmp = temporary(instNumber == mnemonics::SLBP ? 8 : 32);
				_[sPOPTo(tmp)];
				_[*(regizter(bp) + constant(bpOffset)) ^= tmp];
			}
		    }


the ideal code is :   v_0xC = 0;
please help me!
```

**Comment by yegord** [comment]
And what is generated?

**Comment by anywhereyang** [comment]
nothing generated. and this problem exsited   in smartdec

**Comment by yegord** [comment]
If an assignment to a local variable is not used, it is not generated: https://github.com/yegord/snowman/blob/6b766ea54a60a524cca72e857d6a79589ce40553/src/nc/core/ir/cgen/DefinitionGenerator.cpp#L638

You can comment out that if for the purpose of debugging, it should make every assignment visible.

**Comment by anywhereyang** [comment]
i commented out that and commented related assert,  but it not worked, 

it occur some exception !

**Comment by yegord** [comment]
Sorry, I misinformed you: the trick worked a while ago, after which I rewrote reconstruction of expressions, and it got a bit more complicated.

Commenting out the two ifs below and all the asserts that start failing after that seems to do the trick: all the useless staff gets shown.

https://github.com/yegord/snowman/blob/6b766ea54a60a524cca72e857d6a79589ce40553/src/nc/core/ir/cgen/DefinitionGenerator.cpp#L638
https://github.com/yegord/snowman/blob/6b766ea54a60a524cca72e857d6a79589ce40553/src/nc/core/ir/cgen/DefinitionGenerator.cpp#L642
