### ISSUE TITLE
Detect C-NULL-pointers when transforming code.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#17]
Sometimes I see pointers by the generated code looking like '(void **)0', kinda obvious example of a 'NULL' declaration for x86/AMD64. But there did (does?) exist where this actually is a valid pointer.

I guess if we could match NULL-pointers for every arch and replace them by 'NULL' readability would increase for the novice.

**Comment by yegord** [comment]
Won't fix. Following Bjarne, I believe that 0 is the right notation for a null pointer. Until C++11, of course.

There is also a technical argument: NULL is a macro, and likec does not support macros. nullptr would be an option, but I do not like this option: one has to introduce a built-in nullptr_t type, support implicit conversions from/to it, we will lose textual compatibility with C. Is it worth it?

**Comment by nihilus** [comment]
Actually to open up for C-header defines in the decompiler dont besuch a bad udea, including macros. :-)

**Comment by yegord** [comment]
Then we will need a full-fledged C or C++ AST. We do not have one currently. I accept patches. :)

**Comment by nihilus** [comment]
Well as the admin of the boomerang project I see smartdec / snowman as the successor. I don't mind moving to SPb. I guess I am still married according to ZAGS #2 in SPb TBH. So if you'd offer me a fulltime job I'dnt mind at all.

**Comment by yegord** [comment]
Sorry, I am not hiring. And I am not in SPb.
