### ISSUE TITLE
dose snownan handle  stack grow up in custom architecture,

### ISSUE THREAD

**Issue by anywhereyang** [yegord/snowman#170]
hi yegord,  i have get a trouble 。 push instruction  will set esp increase 4, and argument is connected  var, and all referenced is based  ebp , 

stack memory :

24| var2   | ebp +18
20| var1   | ebp +14
1C| var0   | ebp +10
18| arg3   | ebp +c
14| arg2   | ebp +8
10| arg1   | ebp +4
0C| arg0   | ebp +0

,i manual compute  offset ,   but argument is  adverse，，so  i  want to override the Convention to resolve it,  but i don't know where is must be override

**Comment by anywhereyang** [comment]
i have done what you say ,but result incorrect

**Comment by yegord** [comment]
Since I do not know what is the input, what is the result, and what is what you expect, I cannot help you.

**Comment by anywhereyang** [comment]
if you have interesting to try custom architecture ,i can send you all the file that include the executable file of the custom architecture and the idb created by ida proc and the code about snowman

**Comment by yegord** [comment]
On Fri, Jun 01, 2018 at 04:52:37PM -0700, anywhereyang wrote:
> if you have interesting to try custom architecture ,i can send you all
> the file that include the executable file of the custom architecture
> and the idb created by ida proc and the code about snowman 

Well, I do not have IDA. But if you give the file, your version of
Snowman and the range of instructions to decompile, I may have a look.

-- 
Yegor Derevenets

**Comment by anywhereyang** [comment]
hi,yegord, .
i have sended the code to you, and it is used msvc2013 to complie , and see below :

\first   : msvc2013 open  <src/nc/nc.sln> , complie <nc> project
\second: you should change in main_org.cpp line 202
\third :complie <nocode> project  and F5 , result was wrote to <src/nocode/cxx.cc>.


int32_t fun_51ca() {
    int32_t eflags1;
    int32_t* v2;
    int32_t v3;

    fun_2cc8(0xc0, "MainTestHarnessAbp");    //ideal code is : fun_2cc8(  "MainTestHarnessAbp", 0xc0 ) ;
    fun_41e9();
    eflags1 = fun_5f62();
    v2 = *reinterpret_cast<int32_t**>(0x195c + eflags1 * reinterpret_cast<int32_t>("FLASH"));   ///<   ideal code is : 0x195c  + eflags1  *4
    v3 = *v2;
    fun_5b0f(v3);
    return "AML_FLASH";   ///<   ideal code is : return 0
}


MRPOG.APP, the custom executable file
testman.idb,  idb  of  custom virtual machine process exe created by ida6.8
the range of instructions is virtual offset of 0x51CA- 0x5200 and file offset is 0x526C -0x52A ,  it can be chnage in  Pal2Disassembler.cpp line 206


________________________________
发件人: 杨 志平
发送时间: 2018年6月3日 14:00:13
收件人: yegord/snowman
主题: 答复: [yegord/snowman] dose snownan handle stack grow up in custom architecture, (#170)


hi,yegord, .

i have sended the code to you, and it is used msvc2013 to complie , and see below :


\first   : msvc2013 open  <src/nc/nc.sln> , complie <nc> project

\second: you should change in main_org.cpp line 202

\third :complie <nocode> project  and F5 , result was wrote to <src/nocode/cxx.cc>.


int32_t fun_51ca() {
    int32_t eflags1;
    int32_t* v2;
    int32_t v3;

    fun_2cc8(0xc0, "MainTestHarnessAbp");    //ideal code is : fun_2cc8(  "MainTestHarnessAbp", 0xc0 ) ;
    fun_41e9();
    eflags1 = fun_5f62();
    v2 = *reinterpret_cast<int32_t**>(0x195c + eflags1 * reinterpret_cast<int32_t>("FLASH"));   ///<   ideal code is : 0x195c  + eflags1  *4
    v3 = *v2;
    fun_5b0f(v3);
    return "AML_FLASH";   ///<   ideal code is : return 0
}


MRPOG.APP, the custom executable file
testman.idb,  idb  of  custom virtual machine process exe created by ida6.8
the range of instructions is virtual offset of 0x51CA- 0x5200 and file offset is 0x526C -0x52A ,  it can be chnage in  Pal2Disassembler.cpp line 206




________________________________
发件人: yegord <notifications@github.com>
发送时间: 2018年6月2日 20:13:06
收件人: yegord/snowman
抄送: anywhereyang; Author
主题: Re: [yegord/snowman] dose snownan handle stack grow up in custom architecture, (#170)

On Fri, Jun 01, 2018 at 04:52:37PM -0700, anywhereyang wrote:
> if you have interesting to try custom architecture ,i can send you all
> the file that include the executable file of the custom architecture
> and the idb created by ida proc and the code about snowman

Well, I do not have IDA. But if you give the file, your version of
Snowman and the range of instructions to decompile, I may have a look.

--
Yegor Derevenets

―
