### ISSUE TITLE
prebuilt packages do not contains IDA GUI

### ISSUE THREAD

**Issue by Rombersoft** [yegord/snowman#172]
I have been on your site https://derevenets.com/
downloaded archives do not contains IDA GUI. If I open archive on x-archiver I see file with size 0 and folder with two libraries (.so). If extract archive I see only folder with two libraries. Is it done specially?

**Comment by techbliss** [comment]
The two libraries (.so), goes into the idafolder\plugins\*.so

**Comment by yegord** [comment]
Yes, I distribute the plugin, not the IDA itself.

**Comment by Rombersoft** [comment]
who can diassemble for me this assembly x86 arch?
[libpos.so.1.24.0.zip](https://github.com/yegord/snowman/files/2076609/libpos.so.1.24.0.zip)
