### ISSUE TITLE
can you upgrade qt version to qt 5.4.0?

### ISSUE THREAD

**Issue by onesbug** [yegord/snowman#18]
Boost version: 1.57.0
CMake Error at D:/CMake/share/cmake-3.3/Modules/FindQt4.cmake:1326 (message):
Found unsuitable Qt version "5.4.0" from
C:/Qt/Qt5.4.0/5.4/msvc2013/bin/qmake.exe, this code requires Qt 4.x
Call Stack (most recent call first):
CMakeLists.txt:107 (find_package)

Configuring incomplete, errors occurred!
See also "D:/snowman/src/build/CMakeFiles/CMakeOutput.log".

i try to use cmake generate snowman's msvc project,but it tell me only supports Qt 4.x

**Comment by techbliss** [comment]
Ida depends on QT 4.* so if you build it for QT5 it wouldent work with ida,

**Comment by mrexodia** [comment]
Soon ida will use qt 5

**Comment by yegord** [comment]
Could you test https://github.com/yegord/snowman/tree/qt5 ?

**Comment by onesbug** [comment]
it work,i modified CMakeLists.txt:

+++++++++macro(install)
+++++++++endmacro(install)

add_subdirectory(nc)
add_subdirectory(nocode)
add_subdirectory(snowman)

---------------macro(install)
---------------endmacro(install)
