### ISSUE TITLE
MS Visual C++ - Application has requested Runtime to terminate unusually

### ISSUE THREAD

**Issue by BanjoFox** [yegord/snowman#202]
Hey all!

I am trying to run the Snowman standalone on Windows 10.  The app loads okay, but when i try to analyze a binary (512kb) I get a Runtime Error!  - The application has requested the Runtime to terminate in an unusual way.  Please contact the vendor et.al

**Comment by yegord** [comment]
Does it say anything else? Maybe something about an assertion failure?

**Comment by BanjoFox** [comment]
sadly no :(

(( I use Github all the time and forgot it can do screenshots >.<! ))

![image](https://user-images.githubusercontent.com/4459812/70177083-add52d00-16a7-11ea-99a5-319543b9d63a.png)

**Comment by yegord** [comment]
Do you try to decompile the whole executable?
If yes, what are the last 20 lines that `nocode --verbose your_executable.exe` say?

**Comment by BanjoFox** [comment]
ah you know what... I bet the issue is that standalone doesn't support the file (Bootloader).
`Reads ELF, Mach-O, and PE file formats.`

I'm also having the same problem as #158 so I can't use that either... bummer!

**Comment by yegord** [comment]
Yep, unsupported file format must be the reason.
Although, the decompiler should show a message box instead of crashing.
At least it does show on Linux.

**Comment by BanjoFox** [comment]
Oh well :)

Going to close this one.
