### ISSUE TITLE
Snowman crashes when open file

### ISSUE THREAD

**Issue by DreambigOu** [yegord/snowman#208]
I am a beginner of using Snowman and currently using standalone version on Windows 10.
I can start snowman GUI. After selecting the file to be decompile, snowman seems crashed without any warning or error. Th GUI simply disappeared. 

How can I resolve this issue? What are the supported file extension by Snowman?
Is there any specific format for file including binary or assembly to be decompile?
Thanks for the help.

**Comment by yegord** [comment]
Hi Andrew,

ELF, Mach-O, and PE file formats are supported.

You can try to run the command-line decompiler `nocode` on the same file and see what it complains about.

**Comment by DreambigOu** [comment]
Thank you @yegord for the prompt reply. It works. I compile the code to be ELF format. Both GUI and command line can decompile it successfully.
Is there any other places such forum that I can ask questions?

**Comment by yegord** [comment]
> Is there any other places such forum that I can ask questions?

Probably not. I guess, this issue tracker is good enough: I still read it, and probably some other users do.

**Comment by DreambigOu** [comment]
Thank you very much!
