### ISSUE TITLE
arm gcc 4.4 indirect call not detected

### ISSUE THREAD

**Issue by jrmuizel** [yegord/snowman#22]
gcc-4.4 compiles indirect calls to something like this:
    mov     lr, pc
    ldr     pc, [r3, #0]

Snowman seems to miss this being a call because of the mov lr, pc idiom.

Here's a test case:
http://people.mozilla.org/~jmuizelaar/arm-indirect-call.o

**Comment by nihilus** [comment]
Nice catch!

**Comment by nihilus** [comment]
Do you have the source code available as well???

**Comment by yegord** [comment]
While adding support for ARM, I had to get rid of the Return IR statement, because on ARM during IR generation it is not clear, what is a jump, and what is a return.
It seems, now I should get rid of the Call statement. :-)

**Comment by jrmuizel** [comment]
int (*indirect_func)();

int indirect_call()
{
    return indirect_func();
}

From: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40887

**Comment by yegord** [comment]
I added handling of this particular idiom in https://github.com/yegord/snowman/commit/13dea1e4feb311f6e6ef9ba6ac9d52672a27d850.
Ideally, all calls should be represented as ir::Jump, and the decompiler must decide himself, whether a jump is a jump, call, or return.
So far, I do not know how to do this.
