### ISSUE TITLE
Can't save the c++ code

### ISSUE THREAD

**Issue by Bleusyn** [yegord/snowman#222]
I don't see an option to save the .dll file after i edit the code please keep me updated!

**Comment by yegord** [comment]
Hi, probably right click on the C++ edit area, "Save As..." or Ctrl-S is what you want.
Note that it will save only text, not the whole "project" (e.g., mapping from the assembler instructions to the high-level code).
Also, you can copy-paste the code to your favorite editor and save it there.

**Comment by Bleusyn** [comment]
So i can't save it to the dll i originally opened? I had some old Native DLL file i was editing, do you know how i can edit it and have it restored as the original dll i opened?

**Comment by yegord** [comment]
Not sure what you are asking for.
Snowman does not edit DLLs or other native code, it only decompiles into something relatively human-understandable.
You can save the result of the decompilation as text, but not much more.
