### ISSUE TITLE
An interesting way to generate a disassembler automatically through a human readable instruction set architecture file using YAML

### ISSUE THREAD

**Issue by hlide** [yegord/snowman#23]
I was reading [Medusa](https://github.com/wisk/medusa) and the way they generate their disassembler  blows me away! They use some python scripts and a yaml file to auto-generate their disassembler. Not only that, [x86.yaml](https://github.com/wisk/medusa/blob/dev/arch/x86.yaml) covers all instructions up to AVX2, and [arm.yaml](https://github.com/wisk/medusa/blob/dev/arch/arm.yaml) up to ARMv8. Their [scripts](https://github.com/wisk/medusa/tree/dev/gen) generates a header and a source in C++.

What do you think about?

**Comment by nihilus** [comment]
Actually it is a nice idea however what is of interest is how the API looks.

**Comment by yegord** [comment]
Yeah, looks very nice.
