### ISSUE TITLE
switch-case reconstruction.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#24]
It would be nice to reconstruct swich-case-statements for readability.

**Comment by yegord** [comment]
They are reconstructed. If they are not somewhere, it is a bug, and please submit an example.

**Comment by nihilus** [comment]
This:
```        while (1) {
            if (*(struct s0**)((unsigned char)s0_18 + (uint32_t)"") == t0_19) {
                if ((uint32_t)(unsigned char)s0_18->f2 == 2) {
                    if (*(struct s0**)((unsigned char)s0_18 + (uint32_t)"") == a3) {
                        if (*(struct s0**)((unsigned char)s0_18 + (uint32_t)"") == t4_20) {
                            if (*(struct s0**)((unsigned char)s0_18 + 24) == t2_21) {
                                if (*(struct s0**)(unsigned char)(s0_18 + 2) == t3_22) {
                                    if (*(struct s0**)((unsigned char)s0_18 + (uint32_t)"") == a1) {
                                        if (*(struct s0**)((unsigned char)s0_18 + (uint32_t)"") == a2) 
                                            goto addr_0x1fc8_40;
                                    }
                                }
                            }
                        }
                    }
                }
            }
```
should be transformed to a switch-case.

**Comment by yegord** [comment]
I would say, to a compound condition.
Please provide the instructions how to reproduce the issue.

**Comment by nihilus** [comment]
Do you really want to try my MIPS implementation at this stage? =)

**Comment by yegord** [comment]
You can anyway keep this data for the record. Maybe the issue will not go.
It's a little bit pity that the decompiler generates C strings instead of numbers. Do you have a section starting at address zero in MIPS?

**Comment by nihilus** [comment]
@hlide does the 'ftext_start' start at 0?

**Comment by hlide** [comment]
how would I know that? I'm not sure to understand what it means.

**Comment by yegord** [comment]
@nihilus You can just have a look at the list of sections in the GUI.
