### ISSUE TITLE
cqo instruction not handled

### ISSUE THREAD

**Issue by jrmuizel** [yegord/snowman#29]
long q(long a, long b)
{
        return a / b;
}

https://people.mozilla.org/~jmuizelaar/test-cqo.o

**Comment by yegord** [comment]
> cqo instruction not handled

As any other MIPS instruction. :-)

**Comment by nihilus** [comment]
@yegord Talk for your self ;-)

**Comment by yegord** [comment]
@nihilus That's what I am doing. :-)

**Comment by jrmuizel** [comment]
cqo is an x86 instruction
