### ISSUE TITLE
Build fail in ida

### ISSUE THREAD

**Issue by techbliss** [yegord/snowman#31]
Hey @yegord 
I am trying to build snowman for ida with Qt 4.8.7 idasdk6.6 for ida 6.6.
The last two prebuild packages http://derevenets.com/ 
0.6 and 0.7 no one was able to load into ida.Plugin couldent be loaded.
I have rebuild windows Qt 4.8.7 with namespace QT Release

then in snowman
Cmake configure line 
```cmake -G "Visual Studio 12" -D -DCMAKE_BUILD_TYPE=Release -D QT_NAMESPACE=QT -D IDA_PLUGIN_ENABLED=YES -D IDA_64_BIT_EA_T=NO -D NC_QT5=NO ../src```

```cmake --build . ```

fails in command prompt but builds in visual studio.

A note on Cmake configure.
Cmake apparently disregard the =Release flag, and try to nevertheless build as debug. 
I build as Release in visual no trouble.

build is regonised in ida.
but after i switch to snowman windows, ida crash.
looks like some heap problem.
pastie of the crashdump here.
http://pastebin.com/MyGDm2WF

Standalone snowman.exe is working great, just not plugin.

Any ideas ?

EDIT!
I rebuilded Qt 4.8.4 with namespace QT, the one ida uses itself and same issue.

**Comment by yegord** [comment]
Hi, thank you for reporting this.
I uploaded new binary packages, they should work now.
(Apparently, stripping was a bad idea.)

Concerning your build attempt,
1) you must use Visual Studio 2010,
2) you muse use `--config Release` together with `cmake --build .` (there is a note on this in the build instructions).

**Comment by techbliss** [comment]
It builds okay in visual. 2013.
I am not Cmake expert but aint the 


You can choose a build mode (Debug, Release, RelWithDebInfo, or MinSizeRel):
```-D CMAKE_BUILD_TYPE=Release```
the configure for Release.
its however disrergarded when building.Start with Debug

**Comment by yegord** [comment]
`-D CMAKE_BUILD_TYPE=Release` is disregarded when msbuild is used. Use `--config`.

**Comment by techbliss** [comment]
okay thx .
Latest build you added are working.
You can close issue.

**Comment by techbliss** [comment]
Reason for reopening the issue, is that i have builded @nnihilus version with mips support.
https://github.com/nihilus/snowman
It crashed in ida, just like the version before you fix stripping.
Can you tell what you did with stripping, so i can rebuild and test the decompiler with mips support.
regards

**Comment by nihilus** [comment]
@techbliss did you test building from @yegord as well? Else we should close this and open issue on my repo IFF yegords works fine.

**Comment by nihilus** [comment]
Especially interesting since AFAIK the support for C++11 features is limited in VS 2010, else Id build if myself.

**Comment by techbliss** [comment]
@yegord releases works fine, but this is the same issue as i started here, and in the end mips would hopefully be pulled with the original.
I think maybe he means by stripping, is to enable Multi-threaded Debug (/MTd)

**Comment by yegord** [comment]
The problem was that I did stripping. I stopped doing it, and everything started working again.

**Comment by techbliss** [comment]
Cmake is not for the faint of heart can you pinpoint me to the right line.

**Comment by yegord** [comment]
My buildbot that produces binaries for my homepage succeeds with the following:
```
'cmake' '-DCMAKE_INSTALL_PREFIX=install-prefix' '-G' 'Visual Studio 10' '-DQT_NAMESPACE=QT' '-DIDA_PLUGIN_ENABLED=YES' '../snowman/src'
'cmake' '--build' '.' '--config' 'Release'
'cmake' '--build' '.' '--config' 'Release' '--target' 'install'
```

**Comment by techbliss** [comment]
I have tried building @yegord master latest and still getting the error in ida.
I use build lines mentioned 
```
'cmake' '-DCMAKE_INSTALL_PREFIX=install-prefix' '-G' 'Visual Studio 10' '-DQT_NAMESPACE=QT' '-DIDA_PLUGIN_ENABLED=YES' '../snowman/src'
'cmake' '--build' '.' '--config' 'Release'
'cmake' '--build' '.' '--config' 'Release' '--target' 'install'
```

Stansdalone snowman works without flaws.
In ida snowman shows, but if i click a function ida crash.just like before.

i have analyzed the crashdump of the error.maybe some clues.
http://pastebin.com/a8DJm3Si

**Comment by yegord** [comment]
Sorry, no clues. Works for me. I am afraid, without a shell access I will not be able to say much.

**Comment by techbliss** [comment]
Yes i have tried almost all.

well if your on skype and have time sometime in the next days you can add me zadow28.
But leave the issue open for now.
Now im gonna hit the bed.

**Comment by yegord** [comment]
@techbliss BTW, taking into account that you managed to build @nihilus's fork with MSVC 2010, although it currently can't be built with MSVC 2010, I draw a conclusion that you built not with MSVC 2010, and this is probably why you get crashes.

**Comment by techbliss** [comment]
I never tried building it with 2010, only 2013(see first post) and 2015. Snowman works outside ida both versions.cant see why it should be builded only with 2010 
Should it ?

**Comment by yegord** [comment]
Because MSVC 2010 has one runtime library, MSVC 2013 has another runtime library. If you have IDA using one runtime library (the one of MSVC 2010), and its plugin using another runtime library (the one of MSVC 2013), things start go wrong.

**Comment by yegord** [comment]
https://github.com/yegord/snowman/blob/master/doc/build.asciidoc#notes-on-building-ida-plug-in — item 2.

**Comment by techbliss** [comment]
Ahh get it msvc110.dll contra 130 mismatchn.
However ill give it aå go on 2010 tommorow.

**Comment by nihilus** [comment]
@techbliss @yegord seems that MSVC 2010 have issues with namespaces and lamb functions. However it is now fixed for MIPS/Allegrex.

**Comment by techbliss** [comment]
Okay now i have rebuilded everything @nihilus version with vs2010(RELEASE), with vs studio ,that one crashed in ida also.
since there have been issues with getting the decompiler to actuelly select Release version, adressed here https://github.com/nihilus/snowman/issues/31
 i tried building it as Relwthdebuginfo, and that version works flawless in ida.Maybe Build your build bot skips Release part

**Comment by yegord** [comment]
Hmm. Release and RelWithDebInfo must produce literally the same code.
Do the .plw files differ?

**Comment by techbliss** [comment]
yes there is a huge difference 
release = 2 594 KB(2.5mb)
release with debug info = 5 184 KB

**Comment by techbliss** [comment]
Woot i found error.
Release success.

I had the heap error on other apps, and that send me on a investigation.
I developed alot of qt apps for ida,and sometimes i make newer branches of PyQt4 for ida pro.
so i builded windows QT4.8.7 with from scratch with correct vs version.
then latest Qscilla2.with correct vs vs version.
then latest PyQt4 with correct version.that one was really persistence to build as 2008 ( same as prebuild version).

in the end all same version. Msvcr100.dll 
No more runtime errors.
So this issue helped me more than one way.
Issue can be closed 
Thx and regarrds
