### ISSUE TITLE
Assertion failed: DefinitionGenerator.cpp, line 515.

### ISSUE THREAD

**Issue by jrmuizel** [yegord/snowman#32]
Application Specific Information: Assertion failed: ((jump->thenTarget().basicBlock() == thenBB && jump->elseTarget().basicBlock() == elseBB) || (jump->thenTarget().basicBlock() == elseBB && jump->elseTarget().basicBlock() == thenBB)), function makeExpression, file src/nc/core/ir/cgen/DefinitionGenerator.cpp, line 515.

I can send the binary required to reproduce this by email if desired.

**Comment by nihilus** [comment]
Please do

**Comment by nihilus** [comment]
Do you have the src code as well?

**Comment by yegord** [comment]
Yeah, it is a known bug: col.exe test fails with this assertion. If you have another example, please send it to me, maybe it will be simpler to see why this is happening.

**Comment by jrmuizel** [comment]
I don't have the source code and I've sent the binary by email
