### ISSUE TITLE
'expressions' : a namespace with this name does not exist (mips/allegrex related)

### ISSUE THREAD

**Issue by zecoxao** [yegord/snowman#38]
happens in mips and allegrex projects, specifically:
AllegrexInstructionAnalyzer:189,197
MipsInstructionAnalyzer:97,103
in hlide and nihilus projects.
now, i'm completely clueless to how to solve these, so i'm just leaving the issue here.
maybe someone else can fix it
I'm using Visual Studio 2010 with qt 4.8.6 and boost 1.58.

**Comment by hlide** [comment]
can you elaborate the issue you met?

**Comment by hlide** [comment]
and I think you must report it in the right forked repos as yegord's repo is probably not touched by the issue.

**Comment by nihilus** [comment]
I cannot see any issue at L103  in MipsInstructionAnalyzer.cpp

**Comment by hlide** [comment]
Issues reporting on my forked repository is now activated.

**Comment by nihilus** [comment]
same here.

**Comment by zecoxao** [comment]
would you like me to close this then and address the issue on either hlide or nihilus issue report or shall i continue?

**Comment by hlide** [comment]
it is preferable to report the right repo where you were having the issue.

**Comment by zecoxao** [comment]
Ironically, i'm having the issue in BOTH your repos. but i'll use nihilus one, since it's the one most up to date. I'll close this one since it's useless to be open
