### ISSUE TITLE
Is constant folding and propagation working for IR expression?

### ISSUE THREAD

**Issue by hlide** [yegord/snowman#39]
Is constant folding not supposed to simplify this expression `v1= v0 + 0;` into `v1 = v0;`? I have a lot of lines like that because with Allegrex `move $v1, $v0`is indeed encoded as `addiu $v1, $v0, $zero` with `$zero` whatever it is chosen for `$zero` to return a register assigned to constant 0 or simply a constant 0 itself.

Constant propagation is also a feature present?

**Comment by yegord** [comment]
There is some abstract interpretation that can compute the set of values a term can have, in particular, whether the term is a constant.
There is no analysis using mathematical identity laws for rewriting IR expressions.
But there is some rewriting of LikeC expressions.
This particular issue is easy to fix by tweaking BinaryOperator::rewrite(): it should check if one of the operands is zero (Expression::isZero()) and return the other operand, typecasted to the BinaryOperator's result type (BinaryOperator::getType()).

**Comment by yegord** [comment]
This commit should remove zeros from the LikeC code: 494bdb5eacc5d10eebdb32387e74d474807559a2.

**Comment by hlide** [comment]
Cleaner code :+1:

There is only one point I am unsure about (regardless of your commit): does the sequential order of such transformations assure the best result when multiple transformations are involved?

**Comment by yegord** [comment]
My impression is that ordering should not matter: all transformations are monotonous.

**Comment by hlide** [comment]
I am not considering that issue being fixed. There are a lot of simplifications which remain:

1)  0 | x, x | 0 -> x

2)  0 || x, x || 0  -> x, 1 || x, x || 1 -> 1

3) 0 & x, x & 0 -> x

4) 0 && x, x && 0 -> 0, 1 && x, x && 1 -> x 

5) 0 ^ x, x ^ 0 -> x

6) *NOR* ~(0 | x), ~(x | 0) -> *NOT* ~x

I am trying to add them.

**Comment by hlide** [comment]
Another simplification to do:

`if ((uint32_t)(uint1_t)(a2 < 16) != 0)`

in Allegrex (and MIPS), this is due to:
```
sltiu $v0, $a2, 16
bnez $v0, target
```
that kind of pair of instructions can be found in great quantity in a program.

Technically, it means to transform:

1) (uint32_t)(uint1_t)(x ¤ y) != 0 --> (uint1_t)(x ¤ y)

2) (uint32_t)(uint1_t)(x ¤ y) == 0 --> !(uint1_t)(x ¤ y) --> (uint1_t)(x !¤ y)

**Comment by hlide** [comment]
Added patch to https://github.com/yegord/snowman/issues/39#issuecomment-131206395

**Comment by yegord** [comment]
Thanks!

Concerning SHL, SHR, AND, DataflowAnalyzer should be clever enough to infer that the result is zero if one of the arguments is zero, so we should not need rules for them for this case. Did you come across some counterexamples?

**Comment by hlide** [comment]
No I did not check for SHL, SGR and AND, but mostly for OR and NOR cases where I need to do this rewriting. As I was not sure about what it can be. I tend to consider completeness.

There are still some complex rewriting to consider - the one I talked about above. I suspect you need to check the operands of EQ and NE to see a pattern as *(type)<1-bit value> NE/EQ 0*  can be rewritten into *[!]<1-bit value>*. Unless you have a better suggestion?

**Comment by yegord** [comment]
First of all, one needs to rewrite x == 0 to !x and x != 0 to x in a boolean context (if, while). So, one needs to do this rewriting in If::rewrite and While::rewrite. Probably, the rest of typecasts should be removed there as well.

Concerning your patch, let's first drop whatever is already done by constant folding and keep the rest. Once we'll see that we need those rules, we'll fix constant folding. :-)

**Comment by hlide** [comment]
I have also:
```c++
a0_77 = (void*)((int32_t)a2_74 + -1);
```
would it not be reasonable to rewrite `+ -x` into `-x`?

**Comment by yegord** [comment]
On Sat, Aug 15, 2015 at 03:37:31AM -0700, hlide wrote:
> would it not be reasonable to rewrite `+ -x` into `-x`?
Done in be5d2ad1ad62f7063d223cef91d61824d865ab30.

-- 
Yegor Derevenets

**Comment by yegord** [comment]
> `if ((uint32_t)(uint1_t)(a2 < 16) != 0)`

This should be fixed in master.
