### ISSUE TITLE
RFC: External dependencies like libbfd.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#43]
@yegord would you mind if we integrate the CMake-scripts for finding external dependencies like libbfd or libELF?

The ELFparser we have today is good but since different platforms (notably HPPA, Sparc and MIPS) have different extension for their ELF ABI wouldn't it be good to let an external library handle this if found?

**Comment by yegord** [comment]
If the scripts will come with a parser actually using these scripts and having some advantages over the existing parser, then yes.

**Comment by nihilus** [comment]
You mean if there is an advantage to read ELF, COFF, PE, HSO and whatever libbfd has to offer... it is with trying? I am glad your open for this suggestion as this is not only what I want but also a couple of friends of mine suggested as well. :-) (beer) :

**Comment by yegord** [comment]
On Tue, Aug 18, 2015 at 04:49:05PM -0700, Markus Gothe wrote:
> You mean if there is an advantage to read ELF, COFF, PE, HSO and
> whatever libbfd has to offer...

I mean that if you have a parser reading all of that using libbfd, then
I am willing to accept a patch with this parser, together with a CMake
script finding libbfd. But so far I do not see any parser.

-- 
Yegor Derevenets

**Comment by nihilus** [comment]
Roger that... Something like this should make integration easier: http://www.commontk.org/docs/html/ctkMacroBFDCheck_8cmake_source.html

**Comment by nihilus** [comment]
I've been starting to bundle and integrating libbfd under 3rd-party/libbfd fwiw. After I get the CMake-stuff working I will write a parser.

**Comment by nihilus** [comment]
Well that didn't worked out well, so now I am doing a Parser depending on libbfd with FindBfd.cmake.

**Comment by nihilus** [comment]
Now it is able to parse symbols and sections

**Comment by nihilus** [comment]
Need to add relocs
