### ISSUE TITLE
Use the $gp register as a global pointer and not as a local per function.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#45]
On MIPS the $gp register is saved over over calls between functions.
How should this been taken care of? As for now it will become marked as a local variable and then the liveliness analyzer will kill it off.

"For the N32 and N64 ABIs, a function must preserve the $S0-$s7 registers, the global pointer ($gp or $28), the stack pointer ($sp or $29) and the frame pointer ($30). The O32 ABI is the same except the calling function is required to save the $gp register instead of the called function."

**Comment by nihilus** [comment]
Actually some registers beside to global pointer are saved between function calls while others are not...
I guess the fix for this is kinda intrusive.
This should go for Allegrex as well, right @hlide?

**Comment by hlide** [comment]
For Allegrex, OFW uses $gp to store a module address. $k0 is used as a software register flags to check permission to run kernel functions. I never saw an usage of $k1. Allegrex has a set of COP0 registers to help to save/restore some registers in interrupt handler so $k0 and $k1 are never used for that original usage. SONY gcc probably made a mess by mixing O32 and N32: registers names are for O32 but call arguments are 8 as in N32 and not 4 as in O32. So I'm clueless for $gp saving way for Allegrex. Frame pointer can be used as $s8 (frame pointer not mandatory).

**Comment by nihilus** [comment]
OFW? Well for me it result in JALR getting the wrong address in $t9. Which means resolving calls to dynamically Liked binaries like libc doesnt work correctly.

**Comment by hlide** [comment]
Sony PSP OFW = O(fficial) F(irm)W(are). Their OS.

**Comment by yegord** [comment]
If you want $gp to be treated as a global variable, you can make Architecture::isGlobalMemory return true for $gp's memory location.

**Comment by nihilus** [comment]
Ah cool... Just like you did with the return value?

**Comment by yegord** [comment]
Hmm. If I understand correctly what you mean, then no. :)
Just override the Architecture::isGlobalMemory method.

**Comment by nihilus** [comment]
Considered this fixed by 9087b28bf2ed37dde115edad0c9151f5b18219dc
