### ISSUE TITLE
Section names for older ELF files are missing.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#46]
I think this is one drawback with having an own ELF parser. I might find a fix by looking at the one in boomerang albeit.

**Comment by yegord** [comment]
Can't reproduce. Please add an example.

**Comment by nihilus** [comment]
Try the ELF file named 'redir' on my fork.

**Comment by nihilus** [comment]
Beware, it is a MIPS binary compiled back in 2005 for Linux 2.4 (however I have got the source code of it but due to legal 'raisins' it cannot be released'.
