### ISSUE TITLE
Use relocations to disassemble more accurately

### ISSUE THREAD

**Issue by jrmuizel** [yegord/snowman#51]
Snowman gets pretty confused with the following dll:
http://people.mozilla.org/~jmuizelaar/snowman/switch.dll

```c
__declspec(dllexport)
const char *get(int k)
{
        switch (k+1) {
                case 0:
                        return "zero";
                case 1:
                        return "one";
                case 2:
                        return "two";
                case 3:
                        return "three";
                default:
                        return "other";
        }
}

const char *get2(int k)
{
        switch (k) {
                case 0:
                        return "zero";
                case 1:
                        return "one";
                case 2:
                        return "two";
                case 3:
                        return "three";
                default:
                        return "other";
        }
}

__declspec(dllexport)
const char *(*get3)(int k) = get2;

int DllMain(long handle, long reason, void* reserved)
{
        return 1;
}
```

Using the relocations in .reloc we can avoid treating the addresses in the jump table as instructions for disassembly.

**Comment by uxmal** [comment]
@jrmuizel : I wanted to ask your permission to add the DLL you mention above (http://people.mozilla.org/~jmuizelaar/snowman/switch.dll) to the [reko](https://github.com/uxmal/reko) decompiler project as a regression test. I apologize for using this channel; I wasn't sure how else to contact you.

**Comment by jrmuizel** [comment]
@uxmal feel free to use that DLL. You can grab my contact information from my commits in snowman or in some of my other repos.

**Comment by jrmuizel** [comment]
I have a prototype of this up at https://github.com/jrmuizel/snowman/tree/basereloc

**Comment by yegord** [comment]
Looks reasonable. I have written several suggestions on the commit page.

**Comment by jrmuizel** [comment]
I have an updated branch at https://github.com/jrmuizel/snowman/tree/basereloc2 that addresses your comments.

**Comment by yegord** [comment]
Looks good to me. Do you want me to merge it?

**Comment by jrmuizel** [comment]
Yes please.

**Comment by yegord** [comment]
Ok, removed one unnecessary sizeof(), sent to buildbot.

**Comment by yegord** [comment]
Merged.

**Comment by jrmuizel** [comment]
Do you mind adding http://people.mozilla.org/~jmuizelaar/snowman/switch.dll to the test suite as well?

**Comment by yegord** [comment]
Done in 2989b44a20902f23449416d386a48b291fa27fe5. Thanks!
