### ISSUE TITLE
Issue with stack handling.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#53]
How does snowman handle the stack pointer? It seems like instructions/registers trying to access the stack pointer register will fail on MIPS.

**Comment by yegord** [comment]
Each ir::Term's ir::dflow::Value has a property: whether it is a stack pointer and, if yes, what is the difference between its value and the value of the stack pointer before the first statement of the function was executed.

There is a special ir::Intrinsic which always evaluates into a stack pointer having zero difference to the value of the stack pointer at the beginning of the function. You assign the stack pointer register the value of this intrinsic at the beginning of the function by specifying this assignment in the ir::calling::Convention's enterStatements (the assignment is copied inside the function's body during the dataflow analysis).

ir::dflow::DataflowAnalyzer iteratively propagates the property, whether something is a stack pointer, along the dataflow paths. If you have an ir::Dereference of something that ir::dflow::DataflowAnalyzer has recognized as a stack pointer, the analyzer assigns the dereference a memory location in the ir::MemoryDomain::STACK domain.

ir::cgen::DefinitionGenerator will generate local variables for terms with the memory location in the ir::MemoryDomain::STACK.

**Comment by nihilus** [comment]
Hmm... So, afaik it should work just like the SP on ARM.

**Comment by nihilus** [comment]
Ahh, bug in store on MIPS...
