### ISSUE TITLE
Get rid of ir::Choice and ir::Term::KILL

### ISSUE THREAD

**Issue by yegord** [yegord/snowman#55]
They are ugly and not needed.

**Comment by nihilus** [comment]
What do they do?

**Comment by yegord** [comment]
This is their problem. Is is hard to explain what they do. They are just ugly magic.

Essentially, Choice behaves as one Term if its reaching definitions reach the Choice, and as the other Term if they don't. And KILL access type can be given to ir::Touch to make Touch kill reaching definitions of the given term.
