### ISSUE TITLE
Improve IDA plugin to use IDA as disassembler.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#59]
We could make some kinda glue to allow the IDA plugin to use IDA as the disassembly engine which would improve the decompiled code quality.

**Comment by jiamo** [comment]
+1.
The source is : 

	static PyObject* foo_bar3(PyObject* self, PyObject* args, PyObject* kw) {
		static char* kwlist[] = {"i", "d", "s",NULL};
		int iNum = 0;
		double fNum = 2.0f;
		char* str = "thing";
		if (!PyArg_ParseTupleAndKeywords(args,kw,"i|d|s",kwlist,&iNum,&fNum,&str)) {
			printf("ERROR");
			return NULL;
		}
		printf("num is: %d,%f,%s\n",iNum,fNum,str);
		Py_RETURN_NONE;
	}

snowman generate code is : 

    int32_t foo_bar3() {
        int32_t ebx1;
        int32_t ebx2;
        int32_t v3;
        int32_t v4;
        int32_t eax5;

        __i686_get_pc_thunk_bx();
        ebx1 = ebx2 + 0x12ab;
        __asm__("fld qword [ebx+0xffffeee4]");
        __asm__("fstp qword [ebp-0x18]");
        eax5 = fun_46c(v3, v4, ebx1 - 0x1140, ebx1 + 68, (int32_t)"zero stack offset"() - 4 - 12, (int32_t)"zero stack offset"() - 4 - 24, (int32_t)"zero stack offset"() - 4 - 28);
        if (eax5) {
            __asm__("fld qword [ebp-0x18]");
            __asm__("fstp qword [esp+0x8]");
            fun_47c(ebx1 - 0x1134, 0, ebx1 - 0x1140, ebx1 + 68, ebx1 - 0x1146, (int32_t)"zero stack offset"() - 4 - 24, (int32_t)"zero stack offset"() - 4 - 28);
            **(int32_t**)(ebx1 - 8) = **(int32_t**)(ebx1 - 8) + 1;
        } else {
            fun_47c(ebx1 - 0x113a, v4, ebx1 - 0x1140, ebx1 + 68, (int32_t)"zero stack offset"() - 4 - 12, (int32_t)"zero stack offset"() - 4 - 24, (int32_t)"zero stack offset"() - 4 - 28);
        }
        return 0;
    }

While IDA-PRO will generate:

    _UNKNOWN *__cdecl foo_bar3(int a1, int a2, int a3)
    {
      _UNKNOWN *v4; // [sp+2Ch] [bp-2Ch]@2
      int v5; // [sp+3Ch] [bp-1Ch]@1
      double v6; // [sp+40h] [bp-18h]@1
      int v7; // [sp+4Ch] [bp-Ch]@1

      v7 = 0;
      v6 = 2.0;
      v5 = (int)"thing";
      if ( PyArg_ParseTupleAndKeywords(a2, a3, "i|d|s", &kwlist_7992, &v7, &v6, &v5) )
      {
        printf("num is: %d,%f,%s\n", v7, v6, v5);
        ++Py_NoneStruct;
        v4 = &Py_NoneStruct;
      }
      else
      {
        printf("ERROR");
        v4 = 0;
      }
      return v4;
    }

**Comment by nihilus** [comment]
@jiamo This is actually more important for unsupported platforms from Hexrays like PPC and MIPS which both relies upon Capstone (except Allegrex).

So a glue between CAPSTONE and IDA would be the first step.

**Comment by nihilus** [comment]
@jiamo file a new issue about 'fld' and fstp', right @yegord.

**Comment by yegord** [comment]
So, just implement flt, fstp in X86InstructionAnalyzer, and send me a patch.
I do not see any relation with the disassembler here.

**Comment by yegord** [comment]
To clarify.
1. Using IDA as a disassembler (instead of capstone or udis86) is a pain. I know, Alex Fokin tried. :)
2. Using IDA as a source of information about where is the code is sensible, but was mentioned long ago in https://github.com/yegord/snowman/issues/10#issuecomment-112572225.

**Comment by nihilus** [comment]
Ah nice to know... :-(
