### ISSUE TITLE
use issues instead of todo.asciidoc?

### ISSUE THREAD

**Issue by mrexodia** [yegord/snowman#6]
Currently there is a todo file in the repository, but is there a reason not to use issues for those? (I could add the issues if you don't have time for it).

**Comment by yegord** [comment]
I see no direct profit in moving the information from place to another.
However, if you are going to assign a task from todo to yourself and work on it, feel free to create an issue for it.

**Comment by mrexodia** [comment]
Okay, as you wish :)
