### ISSUE TITLE
Why snowman doesn't resolve symbol on OSX?

### ISSUE THREAD

**Issue by Congee** [yegord/snowman#61]
Just decompiled a hello world binary stated in the examples page. Got this:
``` C
// snowman doesn't resolve the symbol
int64_t g100001010 = 0x100000fa0;

void fun_100000f88(int64_t rdi) {
    goto g100001010;
}

int64_t _main() {
    fun_100000f88("Hello, World!");
    return 0;
}

int64_t g100001000 = 0;

void fun_100000fa0() {
    goto g100001000;
}
```
Shouldn't it be the following?:
``` C
int _main() {
    puts("Hello, World!");
    return 0x0;
}
```
Btw, disassembly doesn't produce symbol info in asm code, too.
Any suggestion?

Platform:
OSX 10.10

**Comment by nihilus** [comment]
Is this a Mach-O binary?

**Comment by mrxsaimon** [comment]
I think this is related to https://github.com/yegord/snowman/pull/50.

**Comment by Congee** [comment]
Yes, it has something to do with Mach-O binary.

**Comment by yegord** [comment]
@Congee Could you please provide the input binary?

**Comment by Congee** [comment]
@yegord Well, I don't know how to provide a binary here. So I provide a base64 encoded pastebin page
http://pastebin.com/t6ip5Ara
A hello world compiled with `clang -O2`
``` C
#include <stdio.h>

int main(int argc, char *argv[]) {
    puts("hello");
    return 0;
}
```

**Comment by nihilus** [comment]
By using the dsymtab-patch I get the following:
```
zarathustra:src nietzsche$ nocode/nocode a.out 

int64_t _puts = 0x100000f8c;

void _puts(int64_t rdi) {
    goto _puts;
}

int64_t _main() {
    _puts("hello");
    return 0;
}

int64_t dyld_stub_binder = 0;

void fun_100000f8c() {
    goto dyld_stub_binder;
}

```
