### ISSUE TITLE
IDA plugin broken for ARM Big-Endian.

### ISSUE THREAD

**Issue by nihilus** [yegord/snowman#68]
Seems like the plugin feeds data to the backend in wrong endianess and messes up the disassembly.

**Comment by nihilus** [comment]
Actually it is the call to 'get_many_bytes()' that needs a fixup since it returns bytes in the byte order the image have and we always want our bytes in little endian (since windows only runs on LE machines).

**Comment by yegord** [comment]
Please provide the steps necessary to reproduce the problem.

**Comment by nihilus** [comment]
seems like I was causing this myself.

**Comment by nihilus** [comment]
try these ARMEB ELFs in IDA: http://ftp.acc.umu.se/mirror/debian-misc/debian-armeb/pool/main/a/acct/acct_6.3.99+6.4pre1-3_armeb.deb

**Comment by nihilus** [comment]
'''inf.procName == QLatin1String("ARM")``` will return positive value for both "ARM" and "ARMB" hence catch both of the architectures which is wrong. Guess strncmp() is to prefer here.

**Comment by nihilus** [comment]
One solution might be to add "ARMB" comparsion before "ARM" comparsion (I have no compiler at hands atm).

**Comment by nihilus** [comment]
Something like:
```if(strcmp(inf.procName, "ARM") == 0)```
should do (I am short of a compiler atm).

**Comment by yegord** [comment]
inf.procName is "ARM" in those files. So, the decompiler assumes the architecture is ARM little-endian. Any ideas on how to get from IDA whether a file is big-endian?

**Comment by nihilus** [comment]
This should work: http://reverseengineering.stackexchange.com/questions/6668/determine-endianness-of-file-opened-in-ida

However the problem is still encountered when using the executable / ELF loader.

**Comment by yegord** [comment]
When using the ELF parser, things look alright to me:
```
$ build/nocode/nocode --print-instructions ~/tmp/ac | head -n 20
87f8:   str lr, [sp, #-4]!
87fc:   bl #0x89d8
8800:   bl #0x8a70
8804:   bl #0xb4d4
8808:   pop {pc}
880c:   str lr, [sp, #-4]!
8810:   ldr lr, [pc, #4]
8814:   add lr, pc, lr
8818:   ldr pc, [lr, #8]!
881c:   andeq fp, r0, r0, asr #17
8820:   add ip, pc, #0
8824:   add ip, ip, #0xb000
8828:   ldr pc, [ip, #0x8c0]!
882c:   add ip, pc, #0
8830:   add ip, ip, #0xb000
8834:   ldr pc, [ip, #0x8b8]!
8838:   add ip, pc, #0
883c:   add ip, ip, #0xb000
8840:   ldr pc, [ip, #0x8b0]!
8844:   add ip, pc, #0
```

**Comment by yegord** [comment]
Well, IDA's get_many_bytes swaps bytes for us. As a result, it returns, say, `E5 2D E0 04` (strbteq) instead of 04 E0 2D E5 (push). Probably, we need to unswap them by hand...

**Comment by nihilus** [comment]
Ahh that is why Ive got issues with MIPSEB as well.

**Comment by nihilus** [comment]
Did the cvar.info.mf work out?

**Comment by yegord** [comment]
Yes, mf helps to set the architecture right. Thank you for the hint.
I now have to implement unswapping.

**Comment by nihilus** [comment]
Even IF we dont use get_many_bytes and read byte by byte it will be swapped afaik. Rumors has it that this isnt the case for PPC-BE. Ping @aerosoul94

**Comment by yegord** [comment]
Yes, I noticed that reading byte by byte also gives reordered bytes.
I pushed my fix to issue68 branch.
Once it will pass the regression tests, I will merge it to master.
If it is not the case for PPC, we will invent a workaround, once we will implement support for PPC.

**Comment by nihilus** [comment]
Cool... @aerosoul94 have addes both PPC and SPU-support to snowman.

I'll try the fix on MIPSEB next weekend.

**Comment by nihilus** [comment]
Maybe we should use lread4bytes() instead since it CSN handle the byteswapping?

**Comment by yegord** [comment]
Maybe. If you know a better solution, please write it and make a pull request. :-)

**Comment by yegord** [comment]
Pushed the fix to master.
