### ISSUE TITLE
Suggestion add the generation of IR code without DOT

### ISSUE THREAD

**Issue by UnlimitedChild** [yegord/snowman#69]
Suggestion, to add the generation of IR code without formatting in the DOT descriptors.

**Comment by yegord** [comment]
What do you need it for?

**Comment by UnlimitedChild** [comment]
Hallo, I would like to make a code optimizer, which will use an intermediate representation and other data of the graph execution ...

**Comment by yegord** [comment]
If you want to write an optimizer for decompilation purposes, just access the IR (and whatever is computed for it) from C++.

**Comment by UnlimitedChild** [comment]
Is there any documentation for assistance in pseudo-code?

**Comment by yegord** [comment]
On Wed, Feb 03, 2016 at 09:38:25AM -0800, UnlimitedChild wrote:
> Is there any documentation for assistance in pseudo-code?
No, there is no documentation, sorry. If you write one and submit a
patch, I will gladly accept it.

-- 
Yegor Derevenets
