### ISSUE TITLE
Building on OS X would work, but the Makefile fails and dumps build files into the user directory.

### ISSUE THREAD

**Issue by AlexanderOMara** [yegord/snowman#73]
In short, running the Makefile as-is does something awful on OS X, and dumps the build files directly into the user directory, and then fails to build.

The problem is apparently caused by this line, which produces an empty string on OS X.
```make
BUILD_DIR	!= echo /tmp/snowman.`echo $(CURDIR) | sha1sum | awk '{print $$1}'`
```
(Probably because OS X does not have `sha1sum`.)

When I replaced it with this, building works.
```make
BUILD_DIR	= $(CURDIR)/build-dir
```

Any chance something could be done about this, so that attempting to build this does not clutter the user folder of unsuspecting users?

**Comment by nihilus** [comment]
I don't have this problem on Mavericks. However I cannot find 'sha1sum' on my system.

**Comment by AlexanderOMara** [comment]
> I don't have this problem on Mavericks. However I cannot find 'sha1sum' on my system.

0_o How is that possible? Anyhow, running 10.10.5 Yosemite here.

**Comment by yegord** [comment]
Building Snowman using this Makefile is an undocumented feature and is not guaranteed to work.
Please follow the build instructions: https://github.com/yegord/snowman/blob/master/doc/build.asciidoc

**Comment by AlexanderOMara** [comment]
Oh, OK. Building that was does not clutter up the user directory, and works ok.
