### ISSUE TITLE
intSize in likec defaults to host compiler size without option to override in architecture

### ISSUE THREAD

**Issue by KarlVogel** [yegord/snowman#75]
When working on a port to an 8-bit target, I ran into the issue that the generated code contained a bunch of typecasts. The issue seems to be caused by Tree.cpp defaulting the intSize to the host compiler's sizeof(int), but in this case a better value would be 8-bit.

This caused Tree::integerPromotion to make new 32-bit integers for usualArithmeticConversion on my 8-bit code base, resulting in many typecasts.

I first fixed the issue like this: [intfix](/KarlVogel/snowman/commit/50d649bf6498f043525755acccfc910095d264c0)

but that's actually not a good solution as it would break x86_64.

I guess a better solution would be if the architecture provides a default for the intSize and use that in the CodeGenerator?

**Comment by yegord** [comment]
Yes. Probably, even better place for the size of int is the image::Platform class.
Feel free to submit a patch.

**Comment by nihilus** [comment]
Wouldn't matching the integer size with the architecture's bitsize do?

**Comment by KarlVogel** [comment]
No, because for instance on Linux x86_64 with gcc sizeof(int) is 32 bit, while bitness is 64 bit.

**Comment by nihilus** [comment]
ah, yes it is true... :-(

**Comment by yegord** [comment]
I guess, it can be closed.
