### ISSUE TITLE
make it possible to compile without qt

### ISSUE THREAD

**Issue by rofl0r** [yegord/snowman#80]
i spent around 2 days last week to get qt5 compiling for my distro just to test snowman.
qt is one of the most heavyweight packages in existence and it would be nice not to have to.

so if the the snowman engine source code is not already heavily infected by usage of qt types, templates etc (which i did not check) it should be straightforward and possibly a matter of less than an hour of work to make a terminal app that just takes a binary name as input, does the decompile and dumps it to stdout. it seems that the GUI app is not capable of doing much more than that anyhow, except that it dumps its output in a fancy qt window.

**Comment by mrexodia** [comment]
so, if it's not so much work why don't you do it and do a pull request?

**Comment by rofl0r** [comment]
1) i don't do C++
2) i don't do CMAKE
3) i don't do QT

**Comment by mrexodia** [comment]
so how can you say it will probably be less than an hour of work? :smile:

**Comment by techbliss** [comment]
How can you say Qt is so bad, i Even did a easy tut of building it, 26 pages https://github.com/techbliss/Ida_Pro_Ultimate_Qt_Build_Guide
But if you gonna make a Qt app work without Qt, please post that tut.

**Comment by rofl0r** [comment]
my naive assumption is that (for someone who knows where) that there's something like
form1.cc
which contains
```
form1::on_click_foo() {
snowman_engine.set_input_binary(this.editbox1.text);
snowman_engine.decompile();
this.scrollbox1.text = snowman_engine.get_compiled_text();
}
```
so making a command line utilty would basically just mean copying the 3 lines from on_click_foo and interface it with argc/argv and stdout

**Comment by rofl0r** [comment]
>  How can you say Qt is so bad,
@techbliss i didn't say it's bad, i said it's "heavyweight". i know that you dont care because you dont usually build all your stuff from source.

**Comment by techbliss** [comment]
Actuelly i almost always build from source. 
That way i Learn doing it correct, and im sure it do not have mailware.

**Comment by mrexodia** [comment]
Getting rather pointless here, sorry for that.

@rofl0r I think the engine is not dependent on Qt (not entirely sure about that though). What this would require is a new front end which can obviously be done within a reasonable amount of time. However compiling without Qt might get pretty annoying, especially considering you need to change all the CMake stuff.

**Comment by techbliss** [comment]
If you have sdk latest there is allready QT5 libs with QT namespace, gonna save you some hours.

**Comment by yegord** [comment]
You should be able to build Snowman with the stock Qt from your distribution's repository.
You need Qt in QT namespace only if you want to build the IDA plugin.

**Comment by rofl0r** [comment]
i'm aware that you can build snowman with qt4 and qt5; the point is to do it without either.

i honestly don't see the point of the GUI, it's currently very basic and it appears to me that a command line client would be much more powerful:
for example it would allow you to do batch conversions or automatic analysis of generated binaries, let's you easily interface with your favorite command line tools like awk, sed, less, etc...
without requiring your mouse input for every single file.
and as a bonus you get rid of a dependency that loads several dozen megabytes of shared objects into your RAM.

**Comment by mrexodia** [comment]
I get your point, but 'several dozens' of megabytes is nothing compared to
what snowman is going to use on a decently sized file. Someone told me
there is a command line app (which uses Qt) I didn't confirm this though.

**Comment by yegord** [comment]
On Thu, Mar 17, 2016 at 03:57:36PM -0700, rofl0r wrote:
> i'm aware that you can build snowman with qt4 and qt5; the point is to
> do it without either.
Sorry, I still do not see the point.

If you do not want to build Qt yourself, you can use one from your Linux
distribution. Alternatively, you can download a binary distribution for
you platform from the official Qt website.

If you want a command-line tool, there is already one (nocode).

-- 
Yegor Derevenets

**Comment by mrexodia** [comment]
+1 for nocode
