### ISSUE TITLE
How to use it with MIPS PS2?

### ISSUE THREAD

**Issue by Scorpeg** [yegord/snowman#81]
So with MIPS R5900 (little/big endian)
https://en.wikipedia.org/wiki/Emotion_Engine

As it disassemble something which is complete nonsense. Not supported yet?

**Comment by yegord** [comment]
Hi, Snowman does not support MIPS, sorry.
Pull requests are always welcome.

**Comment by techbliss** [comment]
There are MIPS versions using yegord's snowman as base platform. Not sure why they never made a pullover request

**Comment by mrexodia** [comment]
https://github.com/nihilus/snowman this has MIPS support.

**Comment by yegord** [comment]
Actually, there was a pull request. However, it added both MIPS and Allegrex and was not accompanied by any tests, so, was not merged.

Coming back to the original question, I do not support forks.
