### ISSUE TITLE
Error while opening/decompiling elf file (standalone and ida plugin)

### ISSUE THREAD

**Issue by mbprogrammer** [yegord/snowman#87]
When I try to open an .elf file with the standalone version snowman-v0.0.9-win-x64, I receive the following error:
Offset 0x34: Unknown machine id: 20.

Also when I press F3 in IDA on a function of a .elf disassembeled file, snowman decompiles it as if it's a x86 file, not power pc.

**Comment by jrmuizel** [comment]
Can you make the file available?

**Comment by yegord** [comment]
Snowman does not support Power architecture.
IDA plugin, if the architecture is not the one it knows about, assumes x86.

**Comment by mbprogrammer** [comment]
Yes, I can upload it somewhere and place the link.

**Comment by mbprogrammer** [comment]
The elf file can be downloaded from 
https://www.mediafire.com/?wosmsxi2q7q3yow
the file has been compressed using rar5.
