### ISSUE TITLE
Snowman crash. (Out of memory)

### ISSUE THREAD

**Issue by Karaulov** [yegord/snowman#96]
I try to decompile Game.dll (Warcraft 1.26a) and get error (Out of memory) and IDA crashed. (standalone version also crash with this file)

Game.dll size smaller than 13MB

**Comment by yegord** [comment]
What are you going to do with these 13MB decompiled? :)

**Comment by Karaulov** [comment]
What label question ? This is ERROR.

**Comment by yegord** [comment]
No, it is a question, a pretty frequent one.
Each instruction is translated into multiple IR statements, consisting of multiple subexpressions.
Each subexpression is annotated by the size, value information, type information.
And Snowman does interprocedural analyses, this is why it needs IR (with all annotations) for the whole program at once.
So, it is no wonder that the decompiler needs factor many of the size of the input program memory.

And yes, I will gladly accept patches decreasing memory consumption. :)

**Comment by Karaulov** [comment]
Snowman crashed! (I can show screenshot with error) 
This is error.
