### ISSUE TITLE
Snowman drug smoking?

### ISSUE THREAD

**Issue by Karaulov** [yegord/snowman#97]
Game.dll from Warcraft III 1.26a

IDA(HexRays): http://pastebin.com/WeNW0AmL
IDA(Snowman): http://pastebin.com/jXHymgQz

Why snowman so bad code restores ?

**Comment by Karaulov** [comment]
Line 149: 
 ** esp33 = esp21 - 1 - 1 + 1 - 1 + 1 - 1 - 1 - 1 + 1 - 1 - 1 + 1 - 1 - 1 - 1 - 1 - 1 + 1 - 1 - 1 + 1 - 1 + 1 - 1 - 1 + 1 - 1; **
Wow!?????

**Comment by yegord** [comment]
> Why snowman so bad code restores ?
Because you did not make it better. :)

**Comment by Karaulov** [comment]
But **esp33 = esp21 - 1 - 1 + 1 - 1 + 1 - 1 - 1 - 1 + 1 - 1 - 1 + 1 - 1 - 1 - 1 - 1 - 1 + 1 - 1 - 1 + 1 - 1 + 1 - 1 - 1 + 1 - 1;**  WHAAT????
